### ISSUE TITLE
プロジェクトファイルからYMM4を起動するとクラッシュする

### ISSUE THREAD

**Issue by p-rer** [kotolin-sub/YMM4_Console_Plugin#1]
## 概要

プロジェクトファイルからYMM4を起動すると
`The type initializer for 'YukkuriMovieMaker.Plugin.PluginLoader' threw an exception.`
という例外が起動時に発生する。

![image](https://github.com/user-attachments/assets/33ab1ed7-8d02-4519-95b4-fdbdddc60fd5)

## 原因の推測

YMM4を直接起動するとYMM4の実行ファイルの存在するフォルダがカレントディレクトリになるが、プロジェクトファイルから起動するとプロジェクトファイルの存在するフォルダがカレントディレクトリになるため、[ここ](https://github.com/kotolin-sub/YMM4_Console_Plugin/blob/main/sorce.cs#L17-L18)に於いてファイルの取得に失敗するためと思われる。

**Comment by kotolin-sub** [comment]
該当コードがバージョン依存の物だったので削除して対応いたしました。
